language: node_js
node_js:
  - 14 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - source # build master branch only
# before_install:
#   - sudo apt-get install libpng16-dev
#   - sudu apt-get update
#   - brew install libtool automake autoconf nasm
#   - brew install libpng16-dev
script:
  - hexo generate
  - echo "www.aye10032.com" > public/CNAME
deploy:
  provider: pages
  cleanup: false
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: source
  local-dir: public
